@baseUrl = http://localhost:3333
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWduIjp7InN1YiI6IjY5ZDk1MDE5LTk2NDgtNDAxNi1iMGE4LTA1MWJhMGU1ZWI2NSJ9LCJpYXQiOjE3MTQ1MTEzMTIsImV4cCI6MTcxNDUxMTkxMn0.1mIcNQjV82w7ZWFIyfjUj5TVT8sQlDAG8yFtoCS7emY

# @name shortenUrl

POST {{baseUrl}}/urls
Content-Type: application/json

{
  "long_url": "https://www.google.com",
  "short_url": "google",
  "user_id": "69d95019-9648-4016-b0a8-051ba0e5eb65"
}

###

# @name getUrlById

GET {{baseUrl}}/urls/{{shortenUrl.response.body.url_id}}
Authorization: {{authorization}}

###

# @name getRedirectUrl

GET {{baseUrl}}/urls/google/redirect
Authorization: {{authorization}}

###

# @name getUserUrls
GET {{baseUrl}}/users/profile/urls
Authorization: {{authorization}}

###

# @name deleteUrl

DELETE {{baseUrl}}/urls/{{shortenUrl.response.body.url_id}}
Authorization: {{authorization}}
